server:
  port: 9091 # 端口

spring:
  application:
    name: order-service # 应用名称

# 配置 Eureka Server 注册中心
eureka:
  instance:
    prefer-ip-address: true       # 是否使用 ip 地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # ip:port
  client:
    service-url:                  # 设置服务注册中心地址
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

# 自定义配置
name: order-service-prod-2.0
password: '{cipher}AQCtucBgEfl2K2nWrClLXySOp5xhz6/baECVXOFG9T7V9uWNLgQscU5W0FXBIt764qGaTRKXQHMUd1CGd2z+IWzF0Y9MWdmKqAthtJFCpW0sb9b5Vxcm+qFYnkoc/KcZmxaXj4uk7Mhri3sqWZaExWbiE+NmIFBZAH+H+MGcLaLU2q4SrI2gQXD0lbir6fPSn+pH1cy1cTxvoo0dGQN2bW27/8VkQkEhV3Ym80KKQv0vAAvg/eHPAoxrX2mmmaYkwOX2ggL/YnxvRrwi+TPGkfabBcjNNUQinmza61Tf2W+cnsvE+HdIjdmcXIEtLp2lpxLLI8/WNzdoM56xpXaKwloIGD7Dc0hjtS0A50DdZXp7SCw2foH/Vg5sexuEd07Oows='
